name: Calling a RW
on: [workflow_dispatch]
jobs: 
  greet-alice: 
    uses: ./.github/workflows/greeting.yml
    with:
      username: Alice
  greet-john: 
    uses: ./.github/workflows/greeting.yml
    with:
      username: John
